version: '3.8'

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  back_end:
    build: ./back_end
#    restart: always
    volumes:
      - ./back_end:/app
      - static:/app/static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db

  front_end:
    build: ./front_end
    volumes:
      - ./front_end/:/app/result_build/

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front_end/build:/usr/share/nginx/html/
      - ./static:/app/static/
      - media:/app/media/
    ports:
      - "80:80"
    depends_on:
      - back_end
      - front_end

volumes:
  postgres_data:
  static:
  media:
