version: '3.9'

services:

  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  back_end:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/back_end/Dockerfile
    depends_on:
      - db
    command: >
      sh -c "gunicorn back_end.wsgi:application --bind 0.0.0.0:8000"
#    entrypoint: /app/docker/back_end/wsgi-entrypoint.sh
    volumes:
      - static_volume:/app/back_end/django_static
#    expose:
#      - 8000
#    ports:
#      - "8000:8000"

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/back_end/django_static
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      - back_end

volumes:
  static_volume:
  postgres_data:
