version: '3.9'

services:

  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  back_end:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/back_end/Dockerfile
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn back_end.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/back_end/django_static

  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/back_end/django_static
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on:
      - back_end

volumes:
  static_volume:
  postgres_data:
