version: "3.9"

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    build: ./back_end
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    volumes:
      - staticfiles:/backend/staticfiles

  nginx:
    build: ./web_server
    restart: always
    volumes:
      - staticfiles:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  staticfiles: