version: '3.8'

services:
  back_end:
    build: ./back_end
    command: gunicorn lesson_management_service.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back_end/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./back_end/.env
    depends_on:
      - db

  frontend:
    build: ./front_end
    command: npm start
    volumes:
      - ./front_end/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - back_end
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - back_end
      - frontend

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
