# Generated by Django 5.0.3 on 2024-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lessonaccess_viewed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaccess',
            name='viewed_time',
            field=models.IntegerField(default=0),
        ),
    ]
