# Generated by Django 5.0.3 on 2024-03-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lessonaccess_viewed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonaccess',
            name='last_viewed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
