# Generated by Django 5.0.3 on 2024-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonaccess_last_viewed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaccess',
            name='last_viewed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
