# Generated by jojoprison on 2024-03-10 00:17

import random

from django.conf import settings
from django.db import migrations
from faker import Faker


def create_fake_data(apps, schema_editor):
    Product = apps.get_model('lessons', 'Product')
    Lesson = apps.get_model('lessons', 'Lesson')
    LessonAccess = apps.get_model('lessons', 'LessonAccess')
    User = apps.get_model(settings.AUTH_USER_MODEL)

    faker = Faker()

    users = [User.objects.create_user(
        faker.user_name(), faker.email(), 'password'
    ) for _ in range(5)]

    products = [Product.objects.create(
        owner=random.choice(users)
    ) for _ in range(3)]

    lessons = [Lesson.objects.create(
        title=faker.sentence(),
        video_link=faker.url(),
        duration=random.randint(10, 300)
    ) for _ in range(4)]

    for lesson in lessons:
        lesson.products.set(
            random.sample(products, random.randint(1, 3))
        )
        lesson.save()

    for user in users:
        for lesson in lessons:
            LessonAccess.objects.create(
                user=user,
                lesson=lesson,
                viewed_time=random.randint(0, lesson.duration),
                viewed=random.choice([True, False]),
                last_viewed_date=faker.date_time_this_year()
            )


class Migration(migrations.Migration):
    dependencies = [
        ('lessons', '0006_alter_lessonaccess_last_viewed_date'),
    ]

    operations = [
        migrations.RunPython(create_fake_data),
    ]
