FROM python:3.10-slim
LABEL authors="jojoprison"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install --upgrade pip && \
    pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --only main --no-root

COPY . ./

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "back_end.wsgi:application"]
